EX7-Yellow-Green-Black to EX7
DCGO2/DCGO pull request #32
Opened 2024-07-31 10:13 UTC by Erdandrej

All yellow, green and black cardEffects from EX7 are implemented, including the new Overclock and Vortex keyword and Familiar tokens.

2024-08-15 23:52 UTC, Michael8818 requested changes

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Fluffymon_EX7_004.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
Should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Fluffymon_EX7_004.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card);
Should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Galemon_EX7_032.cs
> +                           (cardSource.EqualsCardName("Shoto Kazama") || cardSource.EqualsCardName("ShotoKazama")) &&
No need to check for name without space, EqualsCardName method does this for you

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Galemon_EX7_032.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
Should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Galemon_EX7_032.cs
> +                    if (card.Owner.HandCards.Some(IsShotoCardCondition))
Try using CardEffectCommons.HasMatchConditionOwnersHand instead

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Galemon_EX7_032.cs
> +                        yield return ContinuousController.instance.StartCoroutine(CardEffectCommons.PlayPermanentCards(
move this yield return to line 78, in place of the yield return null

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Galemon_EX7_032.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
Should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Galemon_EX7_032.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card);
Should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/GrandGalemon_EX7_034.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
Should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/GrandGalemon_EX7_034.cs
> +                           CardEffectCommons.HasMatchConditionPermanent(CanSelectPermanentCondition);
This is an unnecessary check, since this digimon on board will guarantee a target.

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/GrandGalemon_EX7_034.cs
> +                                CardEffectCommons.IsPermanentExistsOnOwnerBattleAreaDigimon(permanent, card));
Use CardEffectCommons.IsOwnerPermanent instead

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/GrandGalemon_EX7_034.cs
> +                cardEffects.Add(activateClass);
Since it is once per turn, you need to set a hashstring

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/GrandGalemon_EX7_034.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card);
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Pteromon_EX7_031.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Tlalocmon_EX7_037.cs
> +                    if (card.Owner.HandCards.Some(CanSelectCardCondition))
use CardEffectCommons.HasMatchConditionOwnersHand instead

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Tlalocmon_EX7_037.cs
> +                return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Tlalocmon_EX7_037.cs
> +
Since there are 2 effects with the same timing it is safest to add a hashstring to each

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Triceramon_EX7_035.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
Should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Triceramon_EX7_035.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Triceramon_EX7_035.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Triceramon_EX7_035.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Pteromon_EX7_031.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
Should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Pteromon_EX7_031.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card);
Should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Black/Gigadramon_EX7_044.cs
> +                return CardEffectCommons.IsExistOnBattleArea(card);
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Black/Jagamon_EX7_045.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Black/Jagamon_EX7_045.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Black/Jazamon_EX7_039.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Black/Jazamon_EX7_039.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Black/Jazardmon_EX7_042.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Black/Jazardmon_EX7_042.cs
> +                    if (card.Owner.HandCards.Some(IsHinaCardCondition))
Use CardEffectCommons.HasMatchConditionOwnersHand instead

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Black/Jazarichmon_EX7_046.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Black/Jazarichmon_EX7_046.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Black/Kapurimon_EX7_005.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Black/Kapurimon_EX7_005.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card);
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Black/Tankmon_EX7_043.cs
> +                return CardEffectCommons.IsExistOnBattleArea(card);
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/WindSlicer_EX7_069.cs
> +                activateClass.SetUpActivateClass(null, ActivateCoroutine, -1, true, EffectDescription());
not really a reason for option cards to be optional, just make sure the selections if applicable are "NoSelection: true"

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Zephagamon_EX7_036.cs
> +                       permanent.IsDigimon;
Should just be CardEffectCommons.IsPermanentExistsOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Green/Zephagamon_EX7_036.cs
> +                return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Yellow/Cendrillmon_EX7_030.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Yellow/Chaperomon_EX7_027.cs
> +                    condition: null));
instead of passing a trait string, why not just make it a condition to be used?

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Yellow/Chaperomon_EX7_027.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Yellow/Chaperomon_EX7_027.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Yellow/Familiar_EX7_030_token.cs
> +                           CardEffectCommons.HasMatchConditionPermanent(CanSelectPermanentCondition);
You can not use IsExistOnBattlerArea for a on deletion effect. You need to use:

CanActivateOnDeletion or CanActivateOnDeletionInheritable respectivly

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Yellow/Piximon_EX7_028.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Yellow/SaberLeomonAce_EX7_029.cs
> +                return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Yellow/SaberLeomonAce_EX7_029.cs
> +                return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Yellow/ShoeShoemon_EX7_025.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Yellow/Shoemon_EX7_024.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Yellow/Starmon_EX7_026.cs
> +                return CardEffectCommons.IsExistOnBattleArea(card) &&
should be IsExistOnBattleAreaDigimon

2024-08-15 23:52 UTC, Michael8818 commented on Assets/CardEffect/EX7/Yellow/WonderStomp_EX7_068.cs
> +                activateClass.SetUpActivateClass(null, ActivateCoroutine, -1, true, EffectDescription());
no need to make effect optional, just have selections be optional. Side note since this effect has a mandatory draw 1, it CAN'T be optional

2024-08-16 07:43 UTC, Erdandrej commented on Assets/CardEffect/EX7/Green/Zephagamon_EX7_036.cs
> +                       permanent.IsDigimon;
A function like that doesn't exist, there is only IsPermanentExistsOnOwnerBattleAreaDigimon and IsPermanentExistsOnOpponentBattleAreaDigimon

2024-08-16 07:49 UTC, Erdandrej commented on Assets/CardEffect/EX7/Green/Zephagamon_EX7_036.cs
> +                       permanent.IsDigimon;
I can create it if you want

2024-08-16 07:58 UTC, Erdandrej commented on Assets/CardEffect/EX7/Green/Zephagamon_EX7_036.cs
> +                       permanent.IsDigimon;
I implemented it already

2024-08-16 13:02 UTC, Michael8818 approved these changes

2024-08-16 13:02 UTC, Michael8818 commented on Assets/CardEffect/EX7/Black/Eldradimon_EX7_047.cs
> +                cardEffects.Add(activateClass);
Since this is once per turn it requires a hashstring set

2024-08-20 02:16 UTC, Michael8818 approved these changes

2024-08-20 02:16 UTC, merged