Bt18 protag hybrids
DCGO2/DCGO pull request #43
Opened 2024-10-06 08:08 UTC by Erdandrej

Added all card effects of the Protagonist Hybrid Decks.

2024-10-10 01:31 UTC, Michael8818 requested changes

2024-10-10 01:31 UTC, Michael8818 commented on Assets/CardEffect/BT18/Black/AncientBeetlemon_BT18_072.cs
> +                    return targetPermanent.TopCard.IsLevel5 && targetPermanent.TopCard.ContainsTraits("Insectoid");
use targetPermanent.EqualsTrait instead

2024-10-10 01:31 UTC, Michael8818 commented on Assets/CardEffect/BT18/Black/Beetlemon_BT18_063.cs
> +                           targetPermanent.TopCard.EqualsCardName("J.P.Shibayama");
When using EqualsCardName you do not need to include a check for no spaces. Method will do that for you

2024-10-10 01:31 UTC, Michael8818 commented on Assets/CardEffect/BT18/Black/JPShibayama_BT18_091.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
use IsExistOnBattleAreaDigimon

2024-10-10 01:31 UTC, Michael8818 commented on Assets/CardEffect/BT18/Black/JPShibayama_BT18_091.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
use IsExistOnBattleAreaDigimon

2024-10-10 01:31 UTC, Michael8818 commented on Assets/CardEffect/BT18/Black/JPShibayama_BT18_091.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
IsExistOnBattleAreaDigimon

2024-10-10 01:31 UTC, Michael8818 commented on Assets/CardEffect/BT18/Black/JPShibayama_BT18_091.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
IsExistOnBattleAreaDigimon

2024-10-10 01:31 UTC, Michael8818 commented on Assets/CardEffect/BT18/Black/KoKabuterimon_BT18_057.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
IsExistOnBattleAreaDigimon

2024-10-10 01:31 UTC, Michael8818 commented on Assets/CardEffect/BT18/Black/KoKabuterimon_BT18_057.cs
> +                    return CardEffectCommons.IsExistOnBattleAreaDigimon(card);
IsExistOnBattleAreaDigimon

2024-10-10 01:31 UTC, Michael8818 commented on Assets/CardEffect/BT18/Black/MetalKabuterimon_BT18_067.cs
> +                           targetPermanent.TopCard.EqualsCardName("J.P.Shibayama");
do not need to check for no spaces

2024-10-10 01:31 UTC, Michael8818 commented on Assets/CardEffect/BT18/Black/RhinoKabuterimon_BT18_070.cs
> +                    return targetPermanent.TopCard.IsLevel4 && targetPermanent.TopCard.ContainsTraits("Hybrid")
use EqualsTrait

2024-10-10 01:31 UTC, Michael8818 commented on Assets/CardEffect/BT18/Black/RhinoKabuterimon_BT18_070.cs
> +                cardEffects.Add(activateClass);
needs SetHashstring

2024-10-10 15:22 UTC, Erdandrej commented on Assets/CardEffect/BT18/Black/JPShibayama_BT18_091.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
JP is a tamer. he'll never be in the battle area as a digimon

2024-10-10 15:24 UTC, Erdandrej commented on Assets/CardEffect/BT18/Black/JPShibayama_BT18_091.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
JP is a tamer. he'll never be in the battle area as a digimon

2024-10-10 15:24 UTC, Erdandrej commented on Assets/CardEffect/BT18/Black/JPShibayama_BT18_091.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
JP is a tamer. he'll never be in the battle area as a digimon

2024-10-10 15:24 UTC, Erdandrej commented on Assets/CardEffect/BT18/Black/JPShibayama_BT18_091.cs
> +                    return CardEffectCommons.IsExistOnBattleArea(card) &&
JP is a tamer. he'll never be in the battle area as a digimon

2024-10-11 00:48 UTC, Michael8818 approved these changes

2024-10-11 00:48 UTC, merged