St17 PR
DCGO2/DCGO pull request #7
Opened 2024-04-16 01:03 UTC by albertvasconcellos

@Michael8818 @burkewm

2024-04-16 20:10 UTC, Michael8818 requested changes
Overall Code looks good, I would make note of some method names could be more clear. Having UseCondition is fine, but having UseCondition1, UseCondition2, etc.... could be named better.

2024-04-16 20:10 UTC, Michael8818 commented on Assets/CardEffect/ST17/Green/Cherubimon_ST17_09.cs
> +                                GManager.instance.userSelectionManager.SetBoolSelection(selectionElements: selectionElements, selectPlayer: card.Owner, selectPlayerMessage: selectPlayerMessage, notSe
Have not tested this but wouldn't this mean you won't be able to select something to delete unless you have a target to play in trash, when realistically they are both may effects so neither depend on each other to trigger or activate.

2024-04-16 23:08 UTC, Michael8818 commented
Terriermon - can not trigger main effect
Wendigomon - deletion triggered, but did not play 1 from trash
Megagargomon ace - triggered at end of any attack
Rapidmon ST17-06 - can select any permanent to receive dp -
Giant Missile - does not prevent unsuspend
Henry Wong - Can trigger its main effect

2024-04-17 03:31 UTC, albertvasconcellos commented
Megagargo Ace can't digivolve over level 4 ST17 Rapidmon but it can digivolve over BT8 Rapidmon (Not seeing Rapidmon name)
Megagargo Ace given option to unsuspend after a permanent digivolves or is played (Timing issue)
Cant digivolve or unsuspend tooltip doesnt stay when turn ends

Rapidmon ST17 security reduction is only 2k not 4k
Fire Rocket not recognizing ST17 Rapidmon as Armor Form

Double typhoon promting to add cards even though it isn't optional
double typhoon not going to battle area after security check (effect works though)

Gargomon effect triggering when anything suspends

cherubimon when digivolve didnt trigger second effect when I had no target to delete

Fire rocket not recognizing Armor form in ST17 magnamon

Movie Veemon not reducing cost of digivolving into ST17 magnamon
ST17 Magna not triggering second part of when digivolving unless the first part happens

2024-04-17 06:33 UTC, albertvasconcellos commented
Megagargomon Ace stops egg from digivolving

2024-04-17 23:56 UTC, merged